from enum import Enum


class IntentType(str, Enum):
    CREATE_TASK = 'CREATE_TASK'
    QUERY_TASKS = 'QUERY_TASKS'
    UPDATE_TASK = 'UPDATE_TASK'
    UPDATE_TASK_STATUS = 'UPDATE_TASK_STATUS'
    DECOMPOSE_TASK = 'DECOMPOSE_TASK'
    GENERAL_CHAT = 'GENERAL_CHAT'
    UNKNOWN = 'UNKNOWN'


class IntentClassifierProvider(str, Enum):
    LLM = 'llm'
    RULE = 'rule'
    SEMANTIC = 'semantic'
    HYBRID = 'hybrid'


class TimeScope(str, Enum):
    TODAY = 'TODAY'
    TOMORROW = 'TOMORROW'
    THIS_WEEK = 'THIS_WEEK'
    OVERDUE = 'OVERDUE'
    ALL = 'ALL'
    CUSTOM = 'CUSTOM'
    UNSPECIFIED = 'UNSPECIFIED'


class ClarificationReason(str, Enum):
    MISSING_TIME_SCOPE = 'MISSING_TIME_SCOPE'
    MISSING_TASK_REFERENCE = 'MISSING_TASK_REFERENCE'
    INVALID_TIME_RANGE = 'INVALID_TIME_RANGE'
    AMBIGUOUS_TIME_EXPRESSION = 'AMBIGUOUS_TIME_EXPRESSION'
    MULTIPLE_TASK_MATCHES = 'MULTIPLE_TASK_MATCHES'
    UNRESOLVED_CONTEXT = 'UNRESOLVED_CONTEXT'
